#!/bin/bash

# Options:
# line-in -> headphone
# line-in -> bt
# line-in -> usb
# bt -> headphone

set -e

# Known devices:
# line-in -> hw:0,2
# headphone -> hw:0,0
# usb -> hw:1,0
# bt -> bluealsa

FORMAT="S16_LE"
CHANNELS=2
RATE=48000
SRC="hw:0,2"     # line-in
DST="hw:0,0"    # headphone

function print_usage() {
	echo "Valid parameters are:"
	echo "    -r: 44100 or 48000"
	echo "    -r: S16_LE or S24_LE"
	echo "    -s/d: alsa device, like for example \"hw:0,0\" or \"bluealsa\""
}

while getopts r:f:s:d: option
do
	case "${option}" in
		f) FORMAT=${OPTARG};;
		r) RATE=${OPTARG};;
		s) SRC=${OPTARG};;
		d) DST=${OPTARG};;
		*) echo "Wrong option $option."
			print_usage
			exit 1
			;;
	esac
done

if [ $RATE -ne 44100 ] && [ $RATE -ne 48000 ]; then
	echo "Invalid rate: $RATE"
	print_usage
	exit 1
fi


if [ "$FORMAT" != "S16_LE" ] && [ "$FORMAT" != "S24_LE" ]; then
	echo "Invalid format: $FORMAT"
	print_usage
	exit 1
fi

echo "Loop $SRC to $DST with $FORMAT @ $RATE"

./headphone dac
./capture on

alsaloop -C $SRC -P $DST -c $CHANNELS -r $RATE -f $FORMAT -t 500000 &
PID=$!

read -p "Press enter to terminate"

kill $PID
