#!/bin/bash

if [ -e ./dabon-cli ]; then
    echo "Using local version"
    DABON=./dabon-cli
else
    echo "Using main version"
    DABON=dabon-cli
fi

$DABON start_tuner /usr/share/dabon-firmwares/rom00_patch.016.bin  /usr/share/dabon-firmwares/fmhd_radio_5_0_4.bin

$DABON fm_tune_frequency 93100

sleep 2

$DABON fm_rsq_status
