name: Build images
run-name: Build ${{ inputs.ref }} at ${{ github.sha }}
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Set up Docker Buildx"
        run: Docker/build.sh
      - name: "Compile and generate images"
        run: Docker/launch.sh "make carplayer_defconfig all"
