name: Build images
run-name: Build ${{ inputs.ref }} at ${{ github.sha }}
on: [workflow_dispatch]
jobs:
  build-images:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Build Docker container"
        run: Docker/setup.sh
      - name: "Compile and generate images"
        run: Docker/launch.sh "make carplayer_defconfig all"
