name: Build images
run-name: ${{ github.event_name }} - ${{ github.ref }} - ${{ github.sha }}
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Set up Docker Buildx"
        run: |
          cd Docker
          ./build.sh
      - name: "Compile and generate images"
        run: |
          cd Docker
          ./launch.sh "make car_player_defconfig all"
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            output/images/boot.vfat
            output/images/Image
            output/images/meson-gxbb-odroidc2.dtb
            output/images/rootfs.tar
            output/images/sdcard.img

